/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumesIndexRouteImport } from './routes/resumes/index'
import { Route as ResumesCreateIndexRouteImport } from './routes/resumes/create/index'
import { Route as ResumesChar91idChar93IndexRouteImport } from './routes/resumes/[id]/index'
import { Route as JobPostingsCreateIndexRouteImport } from './routes/job-postings/create/index'
import { Route as JobPostingsChar91idChar93IndexRouteImport } from './routes/job-postings/[id]/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesCreateIndexRoute = ResumesCreateIndexRouteImport.update({
  id: '/resumes/create/',
  path: '/resumes/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesChar91idChar93IndexRoute =
  ResumesChar91idChar93IndexRouteImport.update({
    id: '/resumes/[id]/',
    path: '/resumes/[id]/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobPostingsCreateIndexRoute = JobPostingsCreateIndexRouteImport.update({
  id: '/job-postings/create/',
  path: '/job-postings/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobPostingsChar91idChar93IndexRoute =
  JobPostingsChar91idChar93IndexRouteImport.update({
    id: '/job-postings/[id]/',
    path: '/job-postings/[id]/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/job-postings/[id]': typeof JobPostingsChar91idChar93IndexRoute
  '/job-postings/create': typeof JobPostingsCreateIndexRoute
  '/resumes/[id]': typeof ResumesChar91idChar93IndexRoute
  '/resumes/create': typeof ResumesCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/job-postings/[id]': typeof JobPostingsChar91idChar93IndexRoute
  '/job-postings/create': typeof JobPostingsCreateIndexRoute
  '/resumes/[id]': typeof ResumesChar91idChar93IndexRoute
  '/resumes/create': typeof ResumesCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/job-postings/[id]/': typeof JobPostingsChar91idChar93IndexRoute
  '/job-postings/create/': typeof JobPostingsCreateIndexRoute
  '/resumes/[id]/': typeof ResumesChar91idChar93IndexRoute
  '/resumes/create/': typeof ResumesCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resumes'
    | '/job-postings/[id]'
    | '/job-postings/create'
    | '/resumes/[id]'
    | '/resumes/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resumes'
    | '/job-postings/[id]'
    | '/job-postings/create'
    | '/resumes/[id]'
    | '/resumes/create'
  id:
    | '__root__'
    | '/'
    | '/resumes/'
    | '/job-postings/[id]/'
    | '/job-postings/create/'
    | '/resumes/[id]/'
    | '/resumes/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
  JobPostingsChar91idChar93IndexRoute: typeof JobPostingsChar91idChar93IndexRoute
  JobPostingsCreateIndexRoute: typeof JobPostingsCreateIndexRoute
  ResumesChar91idChar93IndexRoute: typeof ResumesChar91idChar93IndexRoute
  ResumesCreateIndexRoute: typeof ResumesCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/create/': {
      id: '/resumes/create/'
      path: '/resumes/create'
      fullPath: '/resumes/create'
      preLoaderRoute: typeof ResumesCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/[id]/': {
      id: '/resumes/[id]/'
      path: '/resumes/[id]'
      fullPath: '/resumes/[id]'
      preLoaderRoute: typeof ResumesChar91idChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-postings/create/': {
      id: '/job-postings/create/'
      path: '/job-postings/create'
      fullPath: '/job-postings/create'
      preLoaderRoute: typeof JobPostingsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-postings/[id]/': {
      id: '/job-postings/[id]/'
      path: '/job-postings/[id]'
      fullPath: '/job-postings/[id]'
      preLoaderRoute: typeof JobPostingsChar91idChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
  JobPostingsChar91idChar93IndexRoute: JobPostingsChar91idChar93IndexRoute,
  JobPostingsCreateIndexRoute: JobPostingsCreateIndexRoute,
  ResumesChar91idChar93IndexRoute: ResumesChar91idChar93IndexRoute,
  ResumesCreateIndexRoute: ResumesCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
